{
  "headers": {
    "client_id": "anand",
    "client_secret": "12345",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.37.3",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "8f844e25-b455-4807-b917-7cfd737fda34",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "220"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/flights",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/flights",
  "listenerPath": "/api/*",
  "relativePath": "/api/flights",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/flights",
  "rawRequestPath": "/api/flights",
  "remoteAddress": "/127.0.0.1:58860",
  "requestPath": "/api/flights"
}